apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-1
  namespace: postfix
  labels:
    app: postfix-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix-1
  template:
    metadata:
      labels:
        app: postfix-1
    spec:
      containers:
      - name: postfix-mail
        image: 231139847997.dkr.ecr.us-gov-west-1.amazonaws.com/platform/image/advana/smtprelay:latest
        command: ["/bin/sh", "-c", "tail -f /dev/null"]
        imagePullPolicy: Always
        ports:
        - containerPort: 25
