apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postfix.fullname" . }}
  namespace: {{ template "postfix.namespace" . }}
  labels:
    app: {{ template "postfix.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "postfix.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "postfix.name" . }}
    spec:
      containers:
      - name: {{ template "postfix.name" . }}
        image: '{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}'
        command: ["/bin/sh", "-c", "tail -f /dev/null"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
